// src/app/admin/page.tsx
import type { Metadata } from 'next';
import ProductMetrics from './ProductMetrics';

export const metadata: Metadata = {
  title: 'Admin - My Cosmetics',
};

export default function Page() {
  return (
    <>
      <h1 className="font-bold text-4xl mb-8">Welcome</h1>
      <div className="space-y-16">
        <div className="grid grid-cols-2 md:grid-cols-3 gap-8">
          <div className="p-4 h-24 rounded bg-blue-50 leading-8">
            <p className="text-2xl font-semibold text-gray-500">
              Total Products
            </p>
            <p className="font-bold text-xl">200</p>
          </div>
        </div>

        <ProductMetrics />
      </div>
    </>
  );
}

// src/routes/admin/+page.svelte
<script>
	//@ts-nocheck
	import Chart from 'svelte-frappe-charts';

	let data = {
		labels: ['Sun', 'Mon', 'Tues', 'Wed', 'Thurs', 'Fri', 'Sat'],
		datasets: [
			{
				values: [10, 12, 3, 9, 8, 15, 9]
			}
		]
	};
</script>

<svelte:head>
	<title>Admin - My Cosmetics</title>
</svelte:head>

<h1 class="font-bold text-4xl mb-8">Welcome</h1>
<div class="space-y-16">
	<div class="grid grid-cols-2 md:grid-cols-3 gap-8">
		<div class="p-4 h-24 rounded bg-blue-50 leading-8">
			<p class="text-2xl font-semibold text-gray-500">Total Products</p>
			<p class="font-bold text-xl">200</p>
		</div>
	</div>

	<div>
		<Chart {data} type="line" />
	</div>
</div>
