// my-next-app/src/components/UI/button/AppButton.tsx
import { forwardRef } from "react";

interface Props
  extends React.DetailedHTMLProps<
    React.ButtonHTMLAttributes<HTMLButtonElement>,
    HTMLButtonElement
  > {}

const AppButton = forwardRef<HTMLButtonElement, Props>((props, ref) => {
  const { children, className, ...rest } = props;
  return (
    <button
      className={`bg-white px-4 py-2 rounded text-gray-700 shadow shadow-white/50 transition-all duration-300 hover:translate-y-1 hover:rounded-none focus:ring-4 focus:ring-blue-200 outline-none focus:outline-none ${
        className ?? ""
      }`}
      {...rest}
      ref={ref}
    >
      {children}
    </button>
  );
});

AppButton.displayName = "AppButton";
export default AppButton;

// src/components/UI/button/AppButton.svelte
<script lang="ts">
	export let variant = 'default';
</script>

<button
	on:click
	class="px-4 py-2 rounded shadow shadow-white/50 transition-all duration-300 hover:translate-y-1 hover:rounded-none focus:ring-4 focus:ring-blue-200 outline-none focus:outline-none"
	class:bg-blue-700={variant === 'inverted'}
	class:text-gray-100={variant === 'inverted'}
	class:bg-white={variant === 'default'}
	class:text-gray-700={variant === 'default'}
>
	<slot />
</button>
